name: Deploy to Cloud Run

on:
  push:
    branches:
      - issue1

env:
  PROJECT_ID: ${{ secrets.PROJECT_ID }}
  SERVICE_NAME: mova
  REPOSITORY: mova
  IMAGE_NAME: springboot-app

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Configure Docker to use gcloud as a credential helper
        run: gcloud auth configure-docker asia-northeast3-docker.pkg.dev

      - name: Build and Push Docker image
        run: |
          docker build -t asia-northeast3-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE_NAME .
          docker push asia-northeast3-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE_NAME

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy $SERVICE_NAME \
            --image asia-northeast3-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE_NAME \
            --platform managed \
            --region asia-northeast3 \
            --allow-unauthenticated \
            --set-env-vars "DB_PASSWORD=${{ secrets.DB_PASSWORD }},SECRET=${{ secrets.SECRET }}" \
            --add-cloudsql-instances analytical-poet-461806-t7:asia-northeast3:root
