spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/mova
    username: root
    password: mysql
  thymeleaf:
    cache: false

  #spring data jpa ??
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false
    show-sql: true
    hibernate:
        ddl-auto: update

jwt:
  secret: 4418607030a3ec9c5821253b158042e8b241d6b46830325eaa4d8246b423e3e6

