server:
  port: ${PORT:8080}

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:analytical-poet-461806-t7:asia-northeast3:root
    username: root
    password: ${DB_PASSWORD}
  thymeleaf:
    cache: false

  #spring data jpa ??
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false
    show-sql: true
    hibernate:
        ddl-auto: update

jwt:
  secret: ${SECRET}
  expiration: 86400000
  #4418607030a3ec9c5821253b158042e8b241d6b46830325eaa4d8246b423e3e6


logging:
  level:
    # RestTemplate 자체 로그
    org.springframework.web.client.RestTemplate: DEBUG
    # Spring이 감싸는 HTTP 요청 공장(factory) 로그
    org.springframework.http.client: DEBUG
    # (만약 Apache HttpComponents 사용 시)
    org.apache.http: DEBUG
    org.apache.http.wire: DEBUG