server:
  port: 8080
  error:
    include-message: always

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/mova
    username: root
    password: mysql
  thymeleaf:
    cache: false

  #spring data jpa ??
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update

  cloud:
    gcp:
      project-id: ${GCP_PROJECT_ID}
      storage:
        credentials:
          location: ${GCP_STORAGE_CREDENTIAL_LOCATIONS}
        bucket: ${GCP_STORAGE_BUCKET_NAME}

  GCP_STORAGE_CREDENTIAL_LOCATIONS: classpath:[키파일 이름].json
  GCP_PROJECT_ID: [ 키파일에 명시되어있는 프로젝트 ID ]
  GCP_STORAGE_BUCKET_NAME: [ 생성한 버킷 이름 ]


jwt:
  secret: 4418607030a3ec9c5821253b158042e8b241d6b46830325eaa4d8246b423e3e6


ai:
  api: 
  
logging:
  level:
    # RestTemplate 자체 로그
    org.springframework.web.client.RestTemplate: DEBUG
    # Spring이 감싸는 HTTP 요청 공장(factory) 로그
    org.springframework.http.client: DEBUG
    # (만약 Apache HttpComponents 사용 시)
    org.apache.http: DEBUG
    org.apache.http.wire: DEBUG

